apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project.fullname" . }}-config
  labels:
{{ include "project.labels" . | indent 4 }}
data:
  application.yaml: {{ toYaml .Values.application | indent 2 | trim }}

